App/urls.py
from django.urls import path
from . import views

# Naming application to make linking between different views/apps easier and to eliminate namespace collisions.
app_name = "tasks"

urlpatterns = [
    # name = "name" --> here, i am giving the views funtion a name
    path("", views.name, name="name"),
]

ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls'))
]

App/models.py
from django.db import models

# Create your models here.

class List(models.Model):
    list = models.CharField(max_length=20)

App/views.py
from django.shortcuts import render
# from django.http import HttpResponse, HttpResponseRedirect
from django import forms
# from django.urls import reverse

# Create your views here.

tasks = []

class TaskForms(forms.Form):
    task = forms.CharField(label="Task", max_length=225)

def name(request):
    if request.method == "POST":
        form = TaskForms(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
        else:
            return render(request, 'index.html', {
                "form": form,
            })
        
    return render(request, 'index.html',{
        "task": tasks,
        "form": TaskForms(),
    })

App/templates/index.html
{% extends 'layout.html' %}
    
<!-- Body Section -->
    {% block body %}
        <h1>Your activities</h1>

        <ul>
            {% for task in task %}
                <li>{{ task }}</li>
            {% endfor %}
        </ul>

        <form action="{% url 'tasks:name' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
    {% endblock %}
<!-- End of Body Section -->

App/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDoList App</title>
</head>
<body>
    {% block body %}
    
    {% endblock %}
</body>
</html>